#! /bin/bash
# Command similar to bqueues
# Output example:
# PARTITION  AVAIL    PRIO_TIER    MAX_CPUS_PER_NODE      NODES(A/I/O/T)
# Test*      up       1            UNLIMITED                     0/2/0/2
#
sinfo -o "%10P %8a %12p %20B %.16F"
